# Generated by Django 6.0.4 on 2026-04-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('actvo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.modalidad'),
        ),
    ]
